### ISSUE TITLE
Auto reload

### ISSUE THREAD

**Issue by carloslfu** [gamell/markpress#26]
Hi, this is a great tool. Would be nice to have an option for setup a development server with auto-reloading.

**Comment by gamell** [comment]
@carloslfu good idea. Will add a small `gulp` flow to that end when I have some time.

**Comment by gamell** [comment]
@carloslfu implemented in https://github.com/gamell/markpress/releases/tag/v3.0.1

**Comment by carloslfu** [comment]
Nice!!
